const Return_User_Lang = async () => {
    const d = await fetch('/return_lang', { method: "GET" })
    if (d.ok) {
        const getData = await d.text()
        let User_Language;
      
        if (getData == "undefined") {
            User_Language = "ar";
        } else if (getData == "ar-SA") {
            User_Language = "ar";
        } else if (getData == "en-US") {
            User_Language = "en"
        }else{
            User_Language = "ar"
        }
        return User_Language
    }
}
const Language = {
en:{
Nav_Home : "Home",
Nav_About : "About",
Nav_Exams : "Exams",
Nav_Contact : "Contact",
Nav_Faq : "FAQ",
Nav_Account : "Account",
Nav_Login : "Login",
Nav_Signup : "Signup",
Main_Page_Header : "A NEW EXAM’S SYSTEM",
Main_Page_Header_Paragraph : "Looking For Previous Exams,",
Main_Page_Header_Paragraph_Br : "Extra Questions ? You Arrived At The Right Place !",
Learn_More_Text : "Learn More",
Get_Started_Text : "Get Started",
Scroll_To_See_More : "Scroll To See More",
Why_Edu_Text : "Why EDU ?",
Exam_Quiz_Text : "Exams Quiz",
Exam_Quiz_Paragraph : "Keep Tracking Of Your Educational Level",
Trust_Text : "Trust",
Trust_Text_Paragraph : "In a World Where Reliability is Rare, Trust is Our Foundation.",
Avalible_Text : "24/7 Avalible",
Avalible_Text_Paragraph : "Discover How Much Time You Can Save",
Box_Users_Text : "200K + Users",
Box_Users_Paragraph : "and still counting...",
Box_Free_Text : "100% Free!",
Box_Free_Paragraph : "Forever.",
Box_Courses_Text : "10 + Courses Supported",
Box_Courses_Paragraph : "and still adding...",
Box_200_Text : "200 + Exams & Quizz",
Box_200_Paragrph : "check it now !",
Header_About_Text:  "About Us",
Header_About_Paragraph : "Where Innovation And Excellence Converge We Redefine Standards And Exceed Expectations.",
Header_Best_Text : "We Are The Best In Your Area",
Box_Start_Text : "Start Now For Free",
Box_Start_Paragraph : "Start Now With No Need For Any Cards Or Credit Completely Free",
Box_Simple_Text : "It’s Simple",
Box_Simple_Paragraph : "Sign Up Then You Have It A Complete Library Of Exams",
Box_Time_Text : "Saves time",
Box_Time_Paragraph : "No Need To Spend Hours Searching Decide Right Now !",
About_Me_Text : "About Me",
About_Me_Paragraph : "Actually We Are Not A Team I'm One Person In My First Collage Year Develop This Hole Website From A2Z Starting From UI Ending With Full Website, It's More Than A Personal Project It's An Invitation For You To Explore The Digital Universe...",
About_Me_Paragraph2 : "Here's My Coding Through The Solitary Nights And Designing Through The Inspired Days. Welcome To My Digital Realm!",
User_Dashboard_Text : "Dashboard",
User_Account_Text : "Account",
User_Setting_Text : "Setting",
User_Logout_Text : "Logout",
User_Account_Header_Text : "Account Mangement",
Main_Dashboard_Box_Solved_Text : "Exam Solved",
Main_Dashboard_Box_Pass_Text : "Exam Passed",
Main_Dashboard_Box_Pass_Paragraph : "Keep It Up",
Main_Dashboard_Box_Fail_Text : "Exam's Failed",
Main_Dashboard_Box_Fail_Paragraph : "You Can Try Again",
Main_Dashboard_Box_Rank_Text : "Your Rank Is",
Main_Dashboard_Box_Rank_Paragraph : "We Hope You Get Full Marks !",
Account_Dashboard_Profile_Text : "Profile Picture",
Account_Dashboard_Profile_Paragraph : "Upload new image",
Account_Dashboard_Account_Text : "Account Details",
Account_Dashboard_Account_Username : "Username",
Account_Dashboard_Account_Username_PlaceHolder : "Enter your username",
Account_Dashboard_Account_FirstName : "First name",
Account_Dashboard_Account_FirstName_PlaceHolder : "Enter your first name",
Account_Dashboard_Account_LastName : "Last name",
Account_Dashboard_Account_LastName_PlaceHolder : "Enter your last name",
Account_Dashboard_Account_Collage : "Collage name",
Account_Dashboard_Account_Email : "Email address",
Account_Dashboard_Account_Email_PlaceHolder : "Enter your email address",
Account_Dashboard_Account_Save : "Save changes",
Setting_Dashboard_Account_Created_Text : "Account Created",
Setting_Dashboard_Account_Created_Paragraph : "Years Ago",
Setting_Dashboard_Account_Major_Text : "Your Major",
Setting_Dashboard_Account_Language_Text : "Language",
Contact_Header_Text : "Get in touch",
Contact_Input_Name : "Name",
Contact_Input_Subject : "Subject",
Contact_InputValid : "Looks good!",
Contact_Input_InValid : "Recheck Your Input",
Contact_Send_Button_Text : "Send",
Contact_Input_Message : "Message",
Admin_Dashboard_Dashboard_Text: "Dashboard",
Admin_Dashboard_Setting_Text : "Setting",
Admin_Dashboard_Logout_Text : "Logout",
Admin_Dashboard_Header_Text : "Admin Dashboard",
Admin_Dashboard_InTotal_Text : "In Total :",
Admin_Dashboard_Users_Text : "Users",
Admin_Dashboard_LastMonth_Text : "Last Month :",
Admin_Dashboard_Exam_Text : "Exam",
Admin_Dashboard_Admin_Text : "Admin",
Admin_Dashboard_MangeAdmins_Text : "Manage Admins",
Admin_Dashboard_Add_New_Admin_Text : "Add New Admin",
Admin_Dashboard_MangeAdmins_Name_Text : "Name",
Admin_Dashboard_MangeAdmins_Email_Text : "Email",
Admin_Dashboard_MangeAdmins_Register_Text : "Register Date",
Admin_Dashboard_MangeAdmins_Action_Text : "Actions",
Admin_Dashboard_MangeAdmins_Add_Admin_Text : "Add Admin",
Admin_Dashboard_MangeAdmins_Add_Admin_Email_Text : "Email",
Admin_Dashboard_MangeAdmins_Add_Admin_Button : "Add",
Admin_Dashboard_MangeAdmins_Add_Admin_Warning : "Please Enter Email",
Admin_Dashboard_TopUni_Text : "Top",
Admin_Dashboard_TopUni_Paragraph : "Universities",
Admin_Dashboard_Uni_Name : "University Name",
Admin_Dashboard_Uni_Users_Text : "#Users",
Admin_Dashboard_Exams_Header : "Manage Exams",
Admin_Dashboard_Exams_Add_Exam_Button : "Add New Exam",
Admin_Dashboard_Exams_Section_Text : "Section",
Admin_Dashboard_Exams_Name_Text : "Name",
Admin_Dashboard_Exams_Id_Text : "ID",
Admin_Dashboard_Exams_Actions_Text : "Actions",
Admin_Dashboard_Exams_Add_Exam_Text : "Add Exam",
Admin_Dashboard_Exams_Add_Exam_Section_Text : "Exam Section",
Admin_Dashboard_Exams_Add_Exam_Question_Text : "Question",
Admin_Dashboard_Exams_Add_Exam_Answer_Text : "Answer",
Admin_Dashboard_Exams_Add_Exam_Add_Option_Text : "Add Option",
Admin_Dashboard_Exams_Add_Exam_Add_Question_Text : "Add Question",
Admin_Dashboard_Exams_Add_Exam_Finish_Button : "Finish",
Login_Page_Header_Text : "Login",
Login_Page_Email_Text : "Email",
Login_Page_Password_Text : "Password",
Login_Page_ForgetPassword_Text : "Forgot password?",
Login_Page_LoginButton_Text : "Login",
Login_Page_DontHaveAccount_Text : "Don't have an account?",
Login_Page_DontHaveAccount_Text2 : "Sign up",
Signup_Header_Text : "Sign up",
Signup_Email_Text : "Email",
Signup_UserName_Text : "UserName",
Signup_FirstName_Text : "First Name",
Signup_LastName_Text : "Last Name",
Signup_Major_Text : "Major",
Signup_CollageName_Text : "Collage name",
Signup_Deafult_Option_Text : "Choose One",
Signup_SignupButton_Text : "Signup",
Signup_HaveAccount_Text : "Have an Account ?",
Signup_HaveAccount_Login_Text : "Login",
Forget_Password_Header : "Forget Password",
Forget_Password_SendButton : "Send",
Forget_Password_Remeber_Password : "Remember Password ?",
Forget_Password_Remeber_Password_Login : "Login",
Valid_Code_Header : "OTP Verificattion",
Valid_Code_Verify_Button : "Verify",
ChangePassword_Header_Text : "Change password",
ChangePassword_Tips_Text : "Tips :",
ChangePassword_Tips_Text2 : "Create At least 8 Character Password",
ChangePassword_New_Password_Text : "Your new password",
ChangePassword_Repeat_New_Password_Text : "Repeat password",
ChangePassword_Confirm : "Confirm",
Page_404_Header_Text : "Error, Page Not Found",
View_Exam_Header_Text : "Exams Categories",
View_Exam_Search_Text : "Search...",
View_Exam_Search_Not_Found_Text : "Opps, We Can't Found What You Search For",
View_Exam_View_Exam_Button : "View Exams",
Exam_Page_Question_Text : "Practice Question",
Exam_Page_Grade_Text : "Grade",
Exam_Page_Not_Grade_Text : "Grade : Not Graded",
Exam_Page_Take_Test_Text : "Take Test",
Attend_Exam_Submit_Answer : "Submit Answers",
Attend_Exam_Next_Question : "Next Question",
Attend_Exam_Previous_Question : "Previous",
Footer_Paragraph_Text : "Empowering Minds, Igniting Futures - Edu - Unlocking Knowledge, Inspiring Excellence, and Nurturing Tomorrow's Leaders.",
Footer_Useful_Links_Text : "Useful Links",
Footer_Social_Links_Text : "Social Media",
Footer_Useful_Account_Text : "Account",
Footer_Useful_Contact_Text : "Contact",
Faq_Page_Header_Text : "FAQ",
Faq_Page_Paragraph_Text : "Here Are The Answers To Your Most Common Question's",
Faq_Page_New_Text : "New Around ? Find Answers Here",
Faq_Page_Questions_1 : "Is Edu Free ?",
Faq_Page_Answers_1 : "Yes, Edu Is Totally Free Forever Without Any Credit Or Premium Membership Use Anytime , AnyWhere",
Faq_Page_Questions_2 : "For Which Target Audience Edu Are ?",
Faq_Page_Answers_2 : `Edu Is For Universities Student's "Jordan Universities" Soon Coming For All`,
Faq_Page_Questions_3 : "Can I Change My University Any Time ?",
Faq_Page_Answers_3 : "Simply No, You Must Contact Support In Order To Change Your University So We Can Verify.",
Error_Login_Msg : 'Error',
Error_Login_Msg2 : 'Check Your Credentials',
Alert_Msg : "New Alert",
Alert_Msg_Msg_Send : "Your Meesage Has Been Deliverd",
Alert_Msg_Error : "An Error Has Occurred",
Login_Page_Remember_Me : "Keep me logged in",
    Login_Page_F_Header : "We Help You Get Full Marks",
    Login_Page_D_Paragraph : "We Offer You A Whole Exam,Quiz Library For Free Just Register And Go."
},
ar:{
Nav_Home : "الرئيسية",
Nav_About : "عنّا",
Nav_Exams : "الاختبارات",
Nav_Contact : "تواصل",
Nav_Faq : "الاسئلة",
Nav_Account : "الحساب",
Nav_Login : "تسجيل الدخول",
Nav_Signup : "انشاء حساب",
Main_Page_Header : "نظام اختبارات جديد",
Main_Page_Header_Paragraph : "تبحث عن اختبارات سابقة",
Main_Page_Header_Paragraph_Br : "اسئلة اضافية؟ لقد وصلت إلى المكان الصحيح !",
Learn_More_Text : "أعرف المزيد",
Get_Started_Text : "ابدأ الان",
Scroll_To_See_More : "قم بالتمرير لرؤية المزيد",
Why_Edu_Text : "لماذا نحن",
Exam_Quiz_Text : "الامتحانات والاختبارات",
Exam_Quiz_Paragraph : "استمر في تتبع مستواك التعليمي",
Trust_Text : "ثقة",
Trust_Text_Paragraph : "في عالم تندر فيه الموثوقية، الثقة هي أساسنا .",
Avalible_Text : "متاح 24/7",
Avalible_Text_Paragraph : "اكتشف مقدار الوقت الذي يمكنك توفيره",
Box_Users_Text : "200 مستخدمين + ألف",
Box_Users_Paragraph : "وما زال العد...",
Box_Free_Text : "100٪ مجانا !",
Box_Free_Paragraph : "لمدة الحياة",
Box_Courses_Text : "10 + الدورات المدعومة",
Box_Courses_Paragraph : "ويتم الاضافة...",
Box_200_Text : "200 + الامتحانات والاختبارات",
Box_200_Paragrph : "افحصه الان !",
Header_About_Text:  "عنّا",
Header_About_Paragraph : "حيث يتلاقى الابتكار والتميز، نعيد تعريف المعايير ونتجاوز التوقعات.",
Header_Best_Text : "نحن الأفضل في المنطقة",
Box_Start_Text : "ابدأ الآن مجانًا",
Box_Start_Paragraph : "ابدأ الآن دون الحاجة إلى أي بطاقات أو رصيد مجاني تمامًا",
Box_Simple_Text : "بسيط الاستخدام",
Box_Simple_Paragraph : "قم بالتسجيل ثم تحصل على مكتبة كاملة من الامتحانات",
Box_Time_Text : "يوفر الوقت",
Box_Time_Paragraph :  "! لا حاجة لقضاء ساعات في البحث، قرر الآن",
About_Me_Text : "عَنِّي",
About_Me_Paragraph : "في الواقع، نحن لسنا فريقًا، أنا شخص واحد في سنتي الأولى بالجامعة أقوم بتطوير هذا الموقع من البداية بدءًا من واجهة المستخدم وانتهاءً بالموقع الكامل، إنه أكثر من مجرد مشروع شخصي، إنها دعوة لك لاستكشاف العالم الرقمي ...",
About_Me_Paragraph2 : "! إليكم البرمجة خلال الليالي المنعزلة والتصميم خلال الأيام الملهمة. مرحبًا بكم في عالمي الرقمي",
User_Dashboard_Text : "لوحة المعلومات",
User_Account_Text : "الحساب",
User_Setting_Text : "الاعدادات",
User_Logout_Text : "تسجيل الخروج",
User_Account_Header_Text : "إدارة الحساب",
Main_Dashboard_Box_Solved_Text : "اختبارات تم حلها",
Main_Dashboard_Box_Pass_Text : "اختبارات تم اجتيازها",
Main_Dashboard_Box_Pass_Paragraph : "استمر",
Main_Dashboard_Box_Fail_Text : "اختبارات تم الفشل فيها",
Main_Dashboard_Box_Fail_Paragraph : "يمكنك إعادة المحاولة",
Main_Dashboard_Box_Rank_Text : "تقييمك هو",
Main_Dashboard_Box_Rank_Paragraph : "! نأمل أن تحصل على العلامات الكاملة",
Account_Dashboard_Profile_Text : "الصوره الشخصيه",
Account_Dashboard_Profile_Paragraph : "تحميل صورة جديدة",
Account_Dashboard_Account_Text : "معلومات الحساب",
Account_Dashboard_Account_Username : "أسم المستخدم",
Account_Dashboard_Account_Username_PlaceHolder : "أدخل أسم المستخدم",
Account_Dashboard_Account_FirstName : "الاسم الاول",
Account_Dashboard_Account_FirstName_PlaceHolder : "أدخل الاسم الاول",
Account_Dashboard_Account_LastName : "الاسم الاخير",
Account_Dashboard_Account_LastName_PlaceHolder : "أدخل الاسم الاخير",
Account_Dashboard_Account_Collage : "الجامعة",
Account_Dashboard_Account_Email : "البريد الالكتروني",
Account_Dashboard_Account_Email_PlaceHolder : "أدخل البريد الالكتروني",
Account_Dashboard_Account_Save : "حفظ التغييرات",
Setting_Dashboard_Account_Created_Text : "تاريخ أنشاء الحساب",
Setting_Dashboard_Account_Created_Paragraph : "قبل سنوات",
Setting_Dashboard_Account_Major_Text : "التخصص",
Setting_Dashboard_Account_Language_Text : "اللغة",
Contact_Header_Text : "تواصل معنا",
Contact_Input_Name : "الاسم",
Contact_Input_Subject : "الموضوع",
Contact_InputValid : "يبدو جيدا",
Contact_Input_InValid : "الرجاء التاكد من المدخلات",
Contact_Send_Button_Text : "ارسال",
Contact_Input_Message : "الرسالة",
Admin_Dashboard_Dashboard_Text: "لوحة التحكم",
Admin_Dashboard_Setting_Text : "الاعدادات",
Admin_Dashboard_Logout_Text : "تسجيل الخروج",
Admin_Dashboard_Header_Text : "لوحة التحكم",
Admin_Dashboard_InTotal_Text : ": المجموع",
Admin_Dashboard_Users_Text : "مستخدم",
Admin_Dashboard_LastMonth_Text : ": الشهر الاخير",
Admin_Dashboard_Exam_Text : "أختبار",
Admin_Dashboard_Admin_Text : "مشرف",
Admin_Dashboard_MangeAdmins_Text : "ادارة المشرفين",
Admin_Dashboard_Add_New_Admin_Text : "أضافة مشرف",
Admin_Dashboard_MangeAdmins_Name_Text : "الاسم",
Admin_Dashboard_MangeAdmins_Email_Text : "البريد الالكتروني",
Admin_Dashboard_MangeAdmins_Register_Text : "تاريخ التسجيل",
Admin_Dashboard_MangeAdmins_Action_Text : "الاجراءات",
Admin_Dashboard_MangeAdmins_Add_Admin_Text : "أضافة مشرف",
Admin_Dashboard_MangeAdmins_Add_Admin_Email_Text : "البريد الالكتروني",
Admin_Dashboard_MangeAdmins_Add_Admin_Button : "أضافة",
Admin_Dashboard_MangeAdmins_Add_Admin_Warning : "الرجاء أدخال البريد الالكتروني",
Admin_Dashboard_TopUni_Text : "أعلى",
Admin_Dashboard_TopUni_Paragraph : "جامعات",
Admin_Dashboard_Uni_Name : "الجامعة",
Admin_Dashboard_Uni_Users_Text : "#عدد المستخدمين",
Admin_Dashboard_Exams_Header : "ادارة الاختبارات",
Admin_Dashboard_Exams_Add_Exam_Button : "أضافة اختبار جديد",
Admin_Dashboard_Exams_Section_Text : "القسم",
Admin_Dashboard_Exams_Name_Text : "الاسم",
Admin_Dashboard_Exams_Id_Text : "المعرف",
Admin_Dashboard_Exams_Actions_Text : "الاجراءات",
Admin_Dashboard_Exams_Add_Exam_Text : "أضافة اختبار",
Admin_Dashboard_Exams_Add_Exam_Section_Text : "قسم الاختبار",
Admin_Dashboard_Exams_Add_Exam_Question_Text : "السؤال",
Admin_Dashboard_Exams_Add_Exam_Answer_Text : "الاجابة",
Admin_Dashboard_Exams_Add_Exam_Add_Option_Text : "أضافة خيار",
Admin_Dashboard_Exams_Add_Exam_Add_Question_Text : "أضافة سؤال",
Admin_Dashboard_Exams_Add_Exam_Finish_Button : "انتهاء",
Login_Page_Header_Text : "تسجيل دخول",
Login_Page_Email_Text : "الايميل",
Login_Page_Password_Text : "كلمة المرور",
Login_Page_ForgetPassword_Text : "نسيت كلمة المرور؟",
Login_Page_LoginButton_Text : "تسجيل الدخول",
Login_Page_DontHaveAccount_Text : "لا تمتلك حساب",
Login_Page_DontHaveAccount_Text2 : "أنشاء حساب",
Signup_Header_Text : "انشاء حساب",
Signup_Email_Text : "البريد الالكتروني",
Signup_UserName_Text : "أسم المستخدم",
Signup_FirstName_Text : "ألاسم الاول",
Signup_LastName_Text : "ألاسم الاخير",
Signup_Major_Text : "التخصص",
Signup_CollageName_Text : "أسم الجامعة",
Signup_Deafult_Option_Text : "أختر واحد",
Signup_SignupButton_Text : "تسجيل",
Signup_HaveAccount_Text : "تمتلك حساب ؟",
Signup_HaveAccount_Login_Text : "تسجيل دخول",
Forget_Password_Header : "نسيت كلمة المرور",
Forget_Password_SendButton : "أرسال",
Forget_Password_Remeber_Password : "تذكرت كلمة المرور ؟",
Forget_Password_Remeber_Password_Login : "تسجيل دخول",
Valid_Code_Header : "التحقق",
Valid_Code_Verify_Button : "التحقق",
ChangePassword_Header_Text : "تغيير كلمة المرور",
ChangePassword_Tips_Text : "نصيحة :",
ChangePassword_Tips_Text2 : "قم بإنشاء كلمة مرور مكونة من 8 أحرف على الأقل",
ChangePassword_New_Password_Text : "كلمة المرور الجديدة",
ChangePassword_Repeat_New_Password_Text : "قم باعادة كتابة كلمة المرور",
ChangePassword_Confirm : "تأكيد",
Page_404_Header_Text : "لم يتم ايجاد الصفحة",
View_Exam_Header_Text : "أقسام الاختبارات",
View_Exam_Search_Text : "...البحث",
View_Exam_Search_Not_Found_Text : "لم نستطع ايجاد ما تبحث عنه",
View_Exam_View_Exam_Button : "اظهار الاختبارات",
Exam_Page_Question_Text : "أسئلة للممارسة",
Exam_Page_Grade_Text : "التقييم",
Exam_Page_Not_Grade_Text : "التقييم : لم يتم التقييم",
Exam_Page_Take_Test_Text : "أخذ الاختبار",
Attend_Exam_Submit_Answer : "إرسال الإجابات",
Attend_Exam_Next_Question : "السؤال التالي",
Attend_Exam_Previous_Question : "السابق",
Footer_Paragraph_Text : "تمكين العقول وإضاءة المستقبل - إطلاق العنان للمعرفة وإلهام التميز ورعاية قادة الغد.",
Footer_Useful_Links_Text : "روابط مفيدة",
Footer_Social_Links_Text : "التواصل الاجتماعي",
Footer_Useful_Account_Text : "الحساب",
Footer_Useful_Contact_Text : "التواصل",
Faq_Page_Header_Text : "الاسئلة المطروحة مؤخرا",
Faq_Page_Paragraph_Text : "إليك الإجابات على أسئلتك الأكثر شيوعًا",
Faq_Page_New_Text : "جديد هنا ؟ أعثر على الاجابات هنا",
Faq_Page_Questions_1 : "هل هو مجاني ؟",
Faq_Page_Answers_1 : "نعم، مجاني تمامًا إلى الأبد دون استخدام أي رصيد أو عضوية مميزة في أي وقت وفي أي مكان",
Faq_Page_Questions_2 : "ما هو الجمهور المستهدف ؟",
Faq_Page_Answers_2 : `لطلبة الجامعات "الجامعات الاردنية بشكل الخصوص" قريبا لكل الجامعات`,
Faq_Page_Questions_3 : "هل بالامكان تغيير الجامعة في أي وقت ؟",
Faq_Page_Answers_3 : "ببساطة لا، يجب عليك الاتصال بالدعم لتغيير جامعتك حتى نتمكن من التحقق.",
Error_Login_Msg : 'خطأ',
Error_Login_Msg2 : 'تحقق من معلوماتك',
Alert_Msg : "أشعار جديد",
Alert_Msg_Msg_Send : "تم ارسال رسالتك",
Alert_Msg_Error : "حدث خطأ",
Login_Page_Remember_Me : "تذكرني",
Login_Page_F_Header : "نساعدك في الحصول على العلامات الكاملة",
        Login_Page_D_Paragraph : "نحن نقدم لك اختبارات كاملة، ومكتبة امتحانات مجانًا، فقط قم بالتسجيل والانطلاق."
}
}

let lang;
function setLanguage(language) {

const elements = document.querySelectorAll("[data-lang]");

elements.forEach((element) => {
const translationKey = element.getAttribute("data-lang");
element.style.fontFamily = language === "ar" ? "Cairo" : "Poppins";
element.innerText  = Language[language][translationKey];
if (element.getAttribute("placeholder")) {
element.setAttribute(
"placeholder",
Language[language][translationKey]
);

} else {
element.innerText = Language[language][translationKey];
}
});

};
let l;
 Return_User_Lang().then(User_Language =>{
setLanguage(User_Language.split("-")[0] || "ar")
l = User_Language
});

 function GetLang(){
 Return_User_Lang().then(User_Language =>{
return User_Language || "ar"
})
}

